### ISSUE TITLE
Expand on security of Firebase API Keys

### ISSUE THREAD

**Issue by mirestrepo** [brown-ccv/honeycomb-docs#27]
Add mention to [this doc](https://firebase.google.com/docs/projects/api-keys). We could also change to have all this in a secret.... I'm not 💯 sure that's effective since API keys are exposed to the client. Maybe tightening the recommended limits is all we need to suggest

**Comment by RobertGemmaJr** [comment]
We discovered these are safe to leave ion repo. Are currently stored in a `.env` file that's committed to the repo. I think it makes sense to rewrite documentation to have people store them in `firebase.js` as that's how Firebase gives them to you when you first set things up
